const API_BASE_URL_DEVELOPMENT = 'https://localhost:7215';
const API_BASE_URL_PRODUCTION = 'https://appname.azurewebsites.net';

const ENDPOINTS = {
    GET_ALL_ORDERDETAILS:'get-all-orderdetails',
    GET_ORDERDETAIL_BY_ID:'get-orderdetail-by-id',
    CREATE_ORDERDETAIL:'create-orderdetail',
    UPDATE_ORDERDETAIL:'update-orderdetail',
    DELETE_ORDERDETAIL_BY_ID:'delete-orderdetail-by-id'
};

const development= {
    API_URL_GET_ALL_ORDERDETAILS: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_ORDERDETAILS}`,
    API_URL_GET_ORDERDETAIL_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ORDERDETAIL_BY_ID}`,
    API_URL_CREATE_ORDERDETAIL: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.CREATE_ORDERDETAIL}`,
    API_URL_UPDATE_ORDERDETAIL: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.UPDATE_ORDERDETAIL}`,
    API_URL_DELETE_ORDERDETAIL_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.DELETE_ORDERDETAIL_BY_ID}`
};

const production= {
    API_URL_GET_ALL_ORDERDETAILS: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_ALL_ORDERDETAILS}`,
    API_URL_GET_ORDERDETAIL_BY_ID: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_ORDERDETAIL_BY_ID}`,
    API_URL_CREATE_ORDERDETAIL: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.CREATE_ORDERDETAIL}`,
    API_URL_UPDATE_ORDERDETAIL: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.UPDATE_ORDERDETAIL}`,
    API_URL_DELETE_ORDERDETAIL_BY_ID: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.DELETE_ORDERDETAIL_BY_ID}`
};

const Constants = process.env.NODE_ENV === 'development' ? development : production;
export default Constants;
